# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Active Auctions app

on: push
  # schedule:
    # - cron: '0 14 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: mkdir public
    - uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - run: pip install -r requirements.txt
    - run: python3 scripts/active_auctions.py > public/index.html
    - name: GitHub Pages
      if: success()
      uses: crazy-max/ghaction-github-pages@v2.2.0
      with:
        build_dir: public
        target_branch: gh-pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
