# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Active Auctions app

on: # push
  schedule:
    - cron: '0 14 * 3,4,5,6,7,8,9,10 *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: mkdir public
    - uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - run: pip install -r requirements.txt
    - run: echo "<!doctype html><html><body><h1>Ottoneu Leagues</h1><p><a href="https://wfordh.github.io/ottoneu_auctions/953.html>Harry Caray Memorial</a></p></body></html>" > public/index.html
    - run: python3 scripts/active_auctions.py > public/953.html
    - name: GitHub Pages
      if: success()
      uses: crazy-max/ghaction-github-pages@v2.2.0
      with:
        build_dir: public
        target_branch: gh-pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
